import { GENERATED_MARKER, GENERATED_MARKER_CONTENT } from "../../core/markers.js";
import type { GeneratedFile, GenerateOptions, HarnessSpec, Target, ToolSpec } from "../../core/types.js";
import { blockquote, codeBlock, demoteHeadings, inlineCode, oneLine, renderTable } from "./markdown.js";
import { pythonPackageName, scriptName } from "../python/py.js";
import { describeBinding, displayShellCommand, envDefault, needsApproval, toolEnvRefs, yesNo } from "./spec-utils.js";

export * from "./markdown.js";
export * from "./frontmatter.js";
export * from "./spec-utils.js";

const TARGET_RUN: Record<Target, { dir: string; label: string; cmd: string; note?: string }> = {
  typescript: { dir: "typescript", label: "TypeScript agent", cmd: "cd typescript && npm install && npm start" },
  python: {
    dir: "python",
    label: "Python agent",
    // Placeholder; the real command depends on the console-script name and outDir (see targetRun()).
    cmd: "cd python && uv sync && uv run agent",
    note: "or install with pip; see `python/README.md`",
  },
  mcp: { dir: "mcp-server", label: "MCP server", cmd: "cd mcp-server && npm install && npm start", note: "stdio server; register it in any MCP client" },
  "claude-code": {
    dir: "claude-code",
    label: "Claude Code project config",
    cmd: "cp -R claude-code/CLAUDE.md claude-code/.claude /path/to/your/repo/",
    note: "plus `claude-code/.mcp.json` when present; see `claude-code/README.md`",
  },
};

/**
 * Run line for a target. The Python agent's tools operate on the current directory (or `--root`), unlike the
 * TypeScript and MCP targets which default to the project the harness was generated for, so point `--root`
 * back at the project when the command `cd`s into the generated folder.
 */
function targetRun(t: Target, spec: HarnessSpec, opts: GenerateOptions): { dir: string; label: string; cmd: string; note?: string } {
  const r = TARGET_RUN[t];
  if (t !== "python") return r;
  const script = scriptName(spec.name);
  const parts = opts.outDir.replace(/\\/g, "/").split("/").filter((p) => p !== "" && p !== ".");
  const relative = !opts.outDir.startsWith("/") && !/^[A-Za-z]:/.test(opts.outDir) && !parts.includes("..") && parts.length > 0;
  const root = relative ? Array.from({ length: parts.length + 1 }, () => "..").join("/") : undefined;
  return {
    ...r,
    cmd: `cd python && uv sync && uv run ${script}${root ? ` --root ${root}` : ""}`,
    note: `or \`pip install -e .\` and run \`${script}\` (or \`python -m ${pythonPackageName(spec.name)}\`) from the project root; see \`python/README.md\``,
  };
}

const TARGET_ORDER: Target[] = ["typescript", "python", "mcp", "claude-code"];

function orderedTargets(spec: HarnessSpec): Target[] {
  return TARGET_ORDER.filter((t) => spec.targets.includes(t));
}

function subagentModel(spec: HarnessSpec, model?: string): string {
  return model ?? spec.model.subagentId;
}

// ---------------------------------------------------------------------------
// README.md
// ---------------------------------------------------------------------------

function renderReadme(spec: HarnessSpec, opts: GenerateOptions): string {
  const g = spec.guardrails;
  const out: string[] = [];
  out.push(`# ${oneLine(spec.displayName)}`, "", spec.description.trim(), "");
  out.push("**Goal:** " + oneLine(spec.goal), "");
  out.push(
    "> Generated by `decree-harness` " +
      inlineCode(opts.decreeVersion) +
      ". `decree.json` at the project root is the source of truth: edit it (or run `npx decree-harness refine`) and regenerate with `npx decree-harness generate`. Do not hand-edit generated files you want to keep in sync.",
    "",
  );

  out.push("## Model", "");
  out.push(
    renderTable(
      ["Setting", "Value"],
      [
        ["Model", inlineCode(spec.model.id)],
        ["Effort", spec.model.effort],
        ["Thinking", spec.model.thinking],
        ["Subagent model", inlineCode(spec.model.subagentId)],
      ],
    ),
    "",
  );

  out.push("## Tools", "");
  if (spec.tools.length === 0) out.push("_No tools._", "");
  else {
    out.push(
      renderTable(
        ["Name", "Kind", "Read-only", "Approval", "Source"],
        spec.tools.map((t) => [
          inlineCode(t.name),
          t.kind,
          yesNo(t.readOnly),
          needsApproval(t, g.approvalMode) ? "required" : "no",
          t.source ?? "",
        ]),
      ),
      "",
    );
  }

  out.push("## Subagents", "");
  if (spec.subagents.length === 0) out.push("_None._", "");
  else {
    out.push(
      renderTable(
        ["Name", "When to delegate", "Tools", "Model"],
        spec.subagents.map((s) => [
          inlineCode(s.name),
          oneLine(s.description),
          s.tools.map((n) => inlineCode(n)).join(", "),
          inlineCode(subagentModel(spec, s.model)),
        ]),
      ),
      "",
    );
  }

  out.push("## Guardrails", "");
  out.push(
    `- Approval mode: **${g.approvalMode}**`,
    `- Max turns: ${g.maxTurns}; max output tokens per turn: ${g.maxOutputTokensPerTurn}` +
      (g.maxCostUsd !== undefined ? `; cost cap: $${g.maxCostUsd}` : ""),
    `- Blocked commands: ${g.blockedCommands.length ? g.blockedCommands.map((c) => inlineCode(c)).join(", ") : "none"}`,
    `- Allowed paths: ${g.allowedPaths.length ? g.allowedPaths.map((c) => inlineCode(c)).join(", ") : "none"}`,
    `- Redacted env vars: ${g.redactEnv.length ? g.redactEnv.map((c) => inlineCode(c)).join(", ") : "none"}`,
    "",
  );

  out.push("## Evals", "");
  if (spec.evals.length === 0) out.push("_No eval cases._", "");
  else {
    out.push(
      `${spec.evals.length} case(s) in \`evals.json\`. Run them with \`npx decree-harness eval\`.`,
      "",
      renderTable(
        ["Id", "Input", "Checks"],
        spec.evals.map((e) => [inlineCode(e.id), oneLine(e.input), summarizeExpect(e.expect)]),
      ),
      "",
    );
  }

  out.push("## Generated targets", "");
  const targets = orderedTargets(spec);
  if (targets.length === 0) out.push("_No targets selected._", "");
  for (const t of targets) {
    const r = targetRun(t, spec, opts);
    out.push(`- **${r.label}** (\`${r.dir}/\`): ${inlineCode(r.cmd)}${r.note ? ` (${r.note})` : ""}`);
  }
  if (targets.length) out.push("");
  out.push(
    "Environment: copy `.env.example` to `.env` and fill in the values.",
    "",
    "## Files",
    "",
    "- `harness.md`: full design doc of this harness (system prompt, every tool, guardrails). Review this in PRs.",
    "- `evals.json`: eval cases consumed by the generated eval runners.",
    "- `.env.example`: environment variables the harness reads.",
    "",
    "## Regenerate",
    "",
    codeBlock("npx decree-harness generate", "sh"),
    "",
  );
  return out.join("\n");
}

function summarizeExpect(e: HarnessSpec["evals"][number]["expect"]): string {
  const parts: string[] = [];
  if (e.toolsCalled?.length) parts.push(`calls ${e.toolsCalled.join(", ")}`);
  if (e.toolsNotCalled?.length) parts.push(`never calls ${e.toolsNotCalled.join(", ")}`);
  if (e.contains?.length) parts.push(`contains ${e.contains.map((s) => JSON.stringify(s)).join(", ")}`);
  if (e.notContains?.length) parts.push(`omits ${e.notContains.map((s) => JSON.stringify(s)).join(", ")}`);
  if (e.rubric) parts.push(`rubric: ${oneLine(e.rubric)}`);
  return parts.join("; ");
}

// ---------------------------------------------------------------------------
// .env.example
// ---------------------------------------------------------------------------

const ENV_NAME = /^[A-Za-z_][A-Za-z0-9_]*$/;

function envValue(v: string): string {
  if (v === "") return "";
  if (/[\s#"'`$\\=]/.test(v)) return JSON.stringify(v);
  return v;
}

function renderEnvExample(spec: HarnessSpec): string {
  const out: string[] = [`# Environment for ${oneLine(spec.displayName)}. Copy to .env and fill in.`, "# Secrets are left empty on purpose: never commit real values.", ""];
  const seen = new Set<string>();
  for (const e of spec.env) {
    if (seen.has(e.name)) continue;
    seen.add(e.name);
    for (const line of e.description.split(/\r?\n/)) if (line.trim()) out.push(`# ${line.trim()}`);
    const flags = [e.required ? "required" : "optional", e.secret ? "secret" : null].filter(Boolean).join(", ");
    out.push(`# (${flags})`);
    if (!ENV_NAME.test(e.name)) {
      out.push(`# skipped: ${JSON.stringify(e.name)} is not a valid env var name`, "");
      continue;
    }
    out.push(`${e.name}=${e.secret ? "" : envValue(e.default ?? "")}`, "");
  }
  const extra = toolEnvRefs(spec.tools).filter((n) => !seen.has(n) && ENV_NAME.test(n));
  if (extra.length) {
    out.push("# Referenced by tools but not declared in decree.json env:");
    for (const n of extra) {
      const isSecret = spec.tools.some((t) => t.http?.auth?.env === n);
      out.push(`${n}=${isSecret ? "" : envValue(envDefault(spec, n) ?? "")}`);
    }
    out.push("");
  }
  return out.join("\n").replace(/\n+$/, "\n");
}

// ---------------------------------------------------------------------------
// harness.md
// ---------------------------------------------------------------------------

function renderTool(spec: HarnessSpec, t: ToolSpec): string {
  const out: string[] = [`### ${inlineCode(t.name)}`, "", demoteHeadings(t.description.trim(), 3) || "_No description._", ""];
  out.push(
    renderTable(
      ["Property", "Value"],
      [
        ["Kind", t.kind],
        ["Binding", inlineCode(describeBinding(t))],
        ["Read-only", yesNo(t.readOnly)],
        ["Destructive", yesNo(t.destructive)],
        ["Requires approval (flag)", yesNo(t.requiresApproval)],
        [`Asks for approval (mode: ${spec.guardrails.approvalMode})`, yesNo(needsApproval(t, spec.guardrails.approvalMode))],
        ["Source", t.source ?? ""],
      ],
    ),
    "",
  );
  if (t.http) {
    const h = t.http;
    const lines = [
      `- Method / path: ${inlineCode(`${h.method} ${h.path}`)}`,
      `- Base URL: ${inlineCode(`$${h.baseUrlEnv}`)}${h.defaultBaseUrl ? ` (default ${inlineCode(h.defaultBaseUrl)})` : ""}`,
    ];
    if (h.queryParams?.length) lines.push(`- Query params: ${h.queryParams.map((p) => inlineCode(p)).join(", ")}`);
    if (h.headerParams?.length) lines.push(`- Header params: ${h.headerParams.map((p) => inlineCode(p)).join(", ")}`);
    if (h.bodyParam) lines.push(`- Body param: ${inlineCode(h.bodyParam)}`);
    if (h.auth && h.auth.type !== "none") {
      lines.push(
        `- Auth: ${h.auth.type}${h.auth.env ? ` from ${inlineCode(`$${h.auth.env}`)}` : ""}${h.auth.type === "header" && h.auth.header ? ` in header ${inlineCode(h.auth.header)}` : ""}`,
      );
    }
    out.push(...lines, "");
  }
  if (t.shell) {
    out.push(codeBlock(displayShellCommand(t.shell.command), "sh"), "");
    const extras: string[] = [];
    if (t.shell.cwd && t.shell.cwd !== ".") extras.push(`- cwd: ${inlineCode(t.shell.cwd)}`);
    extras.push(`- Timeout: ${t.shell.timeoutMs ?? 120000} ms`);
    out.push(...extras, "");
  }
  if (t.fs) {
    out.push(`- Root: ${inlineCode(t.fs.root)}${t.fs.maxBytes ? `; max bytes: ${t.fs.maxBytes}` : ""}`, "");
  }
  if (t.inputSchema && Object.keys(t.inputSchema).length > 0) {
    out.push("Input schema:", "", codeBlock(JSON.stringify(t.inputSchema, null, 2), "json"), "");
  } else {
    out.push("_Server/built-in tool: no custom input schema._", "");
  }
  return out.join("\n");
}

function renderHarnessDoc(spec: HarnessSpec, opts: GenerateOptions): string {
  const g = spec.guardrails;
  const c = spec.context;
  const out: string[] = [];
  out.push(`# ${oneLine(spec.displayName)}: harness design`, "");
  out.push(
    `Name: ${inlineCode(spec.name)} · generator: ${spec.provenance.generator} · decree ${inlineCode(spec.provenance.decreeVersion)} (rendered by ${inlineCode(opts.decreeVersion)}) · created ${spec.provenance.createdAt} · profile ${inlineCode(spec.provenance.profileName)}`,
    "",
  );
  out.push(spec.description.trim(), "", "## Goal", "", blockquote(spec.goal.trim()), "");

  out.push("## Model", "");
  out.push(
    renderTable(
      ["Setting", "Value"],
      [
        ["Model", inlineCode(spec.model.id)],
        ["Effort", spec.model.effort],
        ["Thinking", spec.model.thinking],
        ["Subagent model", inlineCode(spec.model.subagentId)],
      ],
    ),
    "",
  );

  out.push("## System prompt", "", codeBlock(spec.systemPrompt, "markdown"), "");

  out.push(`## Tools (${spec.tools.length})`, "");
  if (spec.tools.length === 0) out.push("_No tools._", "");
  for (const t of spec.tools) out.push(renderTool(spec, t));

  out.push(`## Subagents (${spec.subagents.length})`, "");
  if (spec.subagents.length === 0) out.push("_None. The main agent does all the work._", "");
  for (const s of spec.subagents) {
    out.push(
      `### ${inlineCode(s.name)}`,
      "",
      demoteHeadings(s.description.trim(), 3),
      "",
      `- Exposed to the main agent as ${inlineCode(`delegate_to_${s.name.replace(/-/g, "_")}`)}`,
      `- Model: ${inlineCode(subagentModel(spec, s.model))}; effort: ${s.effort ?? "medium"}`,
      `- Tools: ${s.tools.length ? s.tools.map((n) => inlineCode(n)).join(", ") : "none"}`,
      "",
      "System prompt:",
      "",
      codeBlock(s.systemPrompt, "markdown"),
      "",
    );
  }

  out.push("## Guardrails", "");
  out.push(
    renderTable(
      ["Guardrail", "Value"],
      [
        ["Approval mode", g.approvalMode],
        ["Max turns", g.maxTurns],
        ["Max output tokens / turn", g.maxOutputTokensPerTurn],
        ["Max cost (USD)", g.maxCostUsd ?? "unlimited"],
        ["Blocked commands", g.blockedCommands.map((x) => inlineCode(x)).join(", ") || "none"],
        ["Allowed paths", g.allowedPaths.map((x) => inlineCode(x)).join(", ") || "none"],
        ["Redacted env vars", g.redactEnv.map((x) => inlineCode(x)).join(", ") || "none"],
      ],
    ),
    "",
  );

  out.push("## Context strategy", "");
  out.push(
    `- Prompt caching: ${c.caching ? "on (system prompt + tools cached; stable tool order)" : "off"}`,
    `- Compaction: ${c.compaction ? "on (server-side compaction for long sessions)" : "off"}`,
    `- Context editing: ${c.contextEditing ? "on (old tool results are cleared)" : "off"}`,
    `- Memory tool: ${c.memory ? "on" : "off"}`,
    "",
  );

  out.push("## Environment", "");
  if (spec.env.length === 0) out.push("_No environment variables._", "");
  else {
    out.push(
      renderTable(
        ["Name", "Description", "Required", "Secret", "Default"],
        spec.env.map((e) => [inlineCode(e.name), e.description, yesNo(e.required), yesNo(e.secret), e.default !== undefined && !e.secret ? inlineCode(e.default) : ""]),
      ),
      "",
    );
  }

  out.push(`## Evals (${spec.evals.length})`, "");
  if (spec.evals.length === 0) out.push("_No eval cases._", "");
  else {
    out.push(
      renderTable(
        ["Id", "Input", "Expectations", "Tags"],
        spec.evals.map((e) => [inlineCode(e.id), e.input, summarizeExpect(e.expect), (e.tags ?? []).join(", ")]),
      ),
      "",
    );
  }

  out.push("## Planner notes", "");
  const notes = spec.provenance.notes ?? [];
  if (notes.length === 0) out.push("_None._", "");
  else out.push(...notes.map((n) => `- ${n.trim().replace(/\r?\n/g, "\n  ")}`), "");

  return out.join("\n").replace(/\n+$/, "\n");
}

// ---------------------------------------------------------------------------

export function generateCommon(spec: HarnessSpec, opts: GenerateOptions): GeneratedFile[] {
  return [
    { path: "README.md", content: renderReadme(spec, opts).replace(/\n+$/, "\n") },
    { path: "evals.json", content: JSON.stringify(spec.evals, null, 2) + "\n" },
    { path: ".env.example", content: renderEnvExample(spec) },
    { path: "harness.md", content: renderHarnessDoc(spec, opts) },
    // Keeps list_files / search (runtime and generated targets) and the scanner out of the generated harness.
    { path: GENERATED_MARKER, content: GENERATED_MARKER_CONTENT },
  ];
}
