import type { McpModel } from "../model.js";
import { READ_ONLY_ENV, ROOT_ENV } from "../model.js";
import { lit } from "../zod.js";

export function configTs(m: McpModel): string {
  const g = m.spec.guardrails;
  const rootDefault =
    m.rootFromSrc !== null
      ? `path.resolve(HERE, ${lit(m.rootFromSrc)})`
      : "process.cwd()";
  return String.raw`// Generated by decree-harness ${m.decreeVersion}. Runtime configuration for the MCP server.
// Nothing in this server may write to stdout: stdout is the MCP protocol channel.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
/** The generated package directory (parent of src/ and dist/). */
export const PACKAGE_DIR = path.resolve(HERE, "..");

/** Minimal .env loader: KEY=VALUE lines; never overrides variables already set. */
function loadDotEnv(file: string): void {
  let text: string;
  try {
    text = fs.readFileSync(file, "utf8");
  } catch {
    return;
  }
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq <= 0) continue;
    const key = line.slice(0, eq).replace(/^export\s+/, "").trim();
    let value = line.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    if (process.env[key] === undefined) process.env[key] = value;
  }
}
loadDotEnv(path.join(PACKAGE_DIR, ".env"));

export const SERVER_NAME = ${lit(m.serverName)};
export const SERVER_VERSION = ${lit(m.version)};

/** Root of the project the tools operate on. */
export const PROJECT_ROOT = path.resolve(process.env[${lit(ROOT_ENV)}] || ${rootDefault});

/** When set, only read-only tools are registered. */
export const READ_ONLY_MODE = /^(1|true|yes)$/i.test(process.env[${lit(READ_ONLY_ENV)}] ?? "");

export const GUARDRAILS = {
  blockedCommands: ${lit(g.blockedCommands)} as string[],
  allowedPaths: ${lit(g.allowedPaths)} as string[],
  redactEnv: ${lit(g.redactEnv)} as string[],
};

/** Log to stderr (stdout is reserved for the protocol). */
export function log(...args: unknown[]): void {
  console.error("[" + SERVER_NAME + "]", ...args);
}
`;
}
