import type { McpModel } from "../model.js";

export const SDK_VERSION = "^1.30.1";
export const ZOD_VERSION = "^4.1.0";

export function packageJson(m: McpModel): string {
  const pkg = {
    name: m.packageName,
    version: m.version,
    private: true,
    description: `MCP server exposing the ${m.spec.displayName} harness tools and prompts (generated by decree-harness).`,
    type: "module",
    bin: { [m.packageName]: "dist/server.js" },
    scripts: {
      start: "tsx src/server.ts",
      build: "tsc -p .",
      typecheck: "tsc --noEmit",
    },
    engines: { node: ">=18.17" },
    dependencies: {
      "@modelcontextprotocol/sdk": SDK_VERSION,
      zod: ZOD_VERSION,
    },
    devDependencies: {
      "@types/node": "^22.0.0",
      tsx: "^4.20.0",
      typescript: "^5.9.3",
    },
  };
  return JSON.stringify(pkg, null, 2) + "\n";
}

export function tsconfigJson(): string {
  const cfg = {
    compilerOptions: {
      target: "ES2022",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      rootDir: "src",
      outDir: "dist",
      types: ["node"],
    },
    include: ["src/**/*.ts"],
  };
  return JSON.stringify(cfg, null, 2) + "\n";
}

/** Values in .env files are single-line; strip newlines defensively. */
function envLine(s: string): string {
  return s.replace(/[\r\n]+/g, " ").trim();
}

export function envExample(m: McpModel): string {
  const lines = [
    `# Environment for the ${envLine(m.spec.displayName)} MCP server.`,
    "# Copy to .env (loaded from this directory at startup) or set these in your MCP client config.",
    "# Variables already set in the environment win over .env.",
    "",
  ];
  for (const e of m.env) {
    lines.push(`# ${envLine(e.description)}${e.required ? " (required)" : ""}${e.secret ? " [secret]" : ""}`);
    const value = e.secret ? "" : envLine(e.default ?? "");
    lines.push(`${e.required || e.default !== undefined ? "" : "# "}${e.name}=${value}`);
    lines.push("");
  }
  return lines.join("\n");
}
