import type { McpModel } from "../model.js";
import { READ_ONLY_ENV, ROOT_ENV, needsApproval } from "../model.js";

/** Escape a string for a single markdown table cell. */
function cell(s: string): string {
  return s
    .replace(/[\r\n]+/g, " ")
    .replace(/\\/g, "\\\\")
    .replace(/\|/g, "\\|")
    .replace(/</g, "&lt;")
    .trim();
}

/** Inline code span that survives backticks in the content. */
function code(s: string): string {
  const flat = s.replace(/[\r\n]+/g, " ");
  const runs = flat.match(/`+/g) ?? [];
  const fence = "`".repeat(Math.max(0, ...runs.map((r) => r.length)) + 1);
  const pad = flat.startsWith("`") || flat.endsWith("`") ? " " : "";
  return `${fence}${pad}${flat}${pad}${fence}`.replace(/\|/g, "\\|");
}

/** Single-line plain text for headings / prose. */
function text(s: string): string {
  return s.replace(/[\r\n]+/g, " ").trim();
}

export function readmeMd(m: McpModel): string {
  const s = m.spec;
  const name = m.serverName;
  const dir = m.outDirRel !== null ? (m.outDirRel === "." ? "mcp-server" : `${m.outDirRel}/mcp-server`) : "mcp-server";
  const absServer = `/abs/path/to/${dir}/src/server.ts`;
  const secretEnv = m.env.filter((e) => e.secret);

  const envJson: Record<string, string> = {};
  for (const e of m.env) {
    if (e.secret) envJson[e.name] = `\${${e.name}}`;
  }
  envJson[ROOT_ENV] = "/abs/path/to/your/project";
  const desktopEnv: Record<string, string> = {};
  for (const e of m.env) if (e.secret) desktopEnv[e.name] = "...";
  desktopEnv[ROOT_ENV] = "/abs/path/to/your/project";

  const mcpJson = {
    mcpServers: { [name]: { type: "stdio", command: "npx", args: ["tsx", absServer], env: envJson } },
  };
  const desktopJson = {
    mcpServers: { [name]: { command: "npx", args: ["-y", "tsx", absServer], env: desktopEnv } },
  };

  const envFlags = secretEnv.map((e) => ` -e ${e.name}=...`).join("");

  const toolRows = m.tools.map(
    (t) =>
      `| ${code(t.name)} | ${t.kind} | ${t.readOnly ? "yes" : "no"} | ${t.destructive ? "**yes**" : "no"} | ${
        needsApproval(s, t) ? "confirm first" : "-"
      } | ${cell(t.description)} |`,
  );
  const envRows = m.env.map(
    (e) =>
      `| ${code(e.name)} | ${e.required ? "yes" : "no"} | ${e.secret ? "yes" : "no"} | ${
        e.default !== undefined ? code(e.default) : "-"
      } | ${cell(e.description)} |`,
  );
  const promptRows = m.prompts.map((p) => `| ${code(p.name)} | ${cell(p.description)} |`);

  const g = s.guardrails;
  const lines: string[] = [
    `# ${text(s.displayName)} MCP server`,
    "",
    `A standalone [Model Context Protocol](https://modelcontextprotocol.io) server (stdio transport) that exposes the`,
    `**${cell(s.displayName)}** harness tools and prompts, so any MCP client (Claude Code, Claude Desktop, Cursor,`,
    "the Claude API MCP connector via a bridge, ...) can use them against this project.",
    "",
    `> ${cell(s.description)}`,
    "",
    "Generated by [decree-harness](https://www.npmjs.com/package/decree-harness) from `decree.json`.",
    "Re-run `npx decree-harness generate` after editing the spec instead of editing these files by hand.",
    "",
    "## Setup",
    "",
    "```bash",
    `cd ${dir}`,
    "npm install",
    "cp .env.example .env   # then fill in the values (or pass them via your MCP client config)",
    "npm run typecheck      # optional",
    "npm start              # runs the server on stdio (for a quick smoke test; Ctrl+C to stop)",
    "```",
    "",
    "Replace `/abs/path/to/...` below with real absolute paths.",
    "",
    "### Claude Code",
    "",
    "```bash",
    `claude mcp add ${name} -- npx tsx ${absServer}`,
    "```",
    "",
    ...(envFlags
      ? [
          "Pass secrets with `-e` (or put them in `.env` next to this README):",
          "",
          "```bash",
          `claude mcp add ${name}${envFlags} -- npx tsx ${absServer}`,
          "```",
          "",
        ]
      : []),
    "Or share it with your team through a project-scoped `.mcp.json` at the repository root",
    "(`claude mcp add --scope project ...` writes this for you; `${VAR}` values are expanded from the environment):",
    "",
    "```json",
    JSON.stringify(mcpJson, null, 2),
    "```",
    "",
    "### Claude Desktop",
    "",
    "Add to `claude_desktop_config.json` (macOS: `~/Library/Application Support/Claude/`, Windows: `%APPDATA%\\Claude\\`):",
    "",
    "```json",
    JSON.stringify(desktopJson, null, 2),
    "```",
    "",
    "### Cursor and other clients",
    "",
    "Use the same `command`/`args`/`env` in the client's MCP config (Cursor: `.cursor/mcp.json`).",
    "",
    "### Faster, offline-safe startup",
    "",
    "`npx tsx` resolves `tsx` from the client's working directory and may try to download it. For faster startup",
    "(and for clients that launch servers with a minimal environment), build once and run the compiled server:",
    "",
    "```bash",
    `cd ${dir} && npm run build`,
    `claude mcp add ${name}${envFlags} -- node /abs/path/to/${dir}/dist/server.js`,
    "```",
    "",
    "## Tools",
    "",
    "| Tool | Kind | Read-only | Destructive | Approval | Description |",
    "|---|---|---|---|---|---|",
    ...(toolRows.length > 0 ? toolRows : ["| - | - | - | - | - | This harness has no client-executable tools. |"]),
    "",
    "Tool annotations (`readOnlyHint`, `destructiveHint`, `idempotentHint`, `openWorldHint`) are set from the spec so",
    "clients can decide what to auto-approve. Approval itself is handled by your MCP client: destructive tools say so in",
    "their description; configure your client to always ask before running them.",
    "",
    ...(m.skipped.length > 0
      ? [
          "Not exposed: " + m.skipped.map((t) => `${code(t.name)} (${t.kind})`).join(", ") + ".",
          "Web search, web fetch, and memory are provided by the client itself (e.g. Claude Code's built-in tools), so",
          "this server does not duplicate them.",
          "",
        ]
      : []),
    ...(s.subagents.length > 0
      ? [
          "Subagents are not tools here (they need their own model loop); each is exposed as a prompt instead.",
          "",
        ]
      : []),
    "## Prompts",
    "",
    "| Prompt | Description |",
    "|---|---|",
    ...promptRows,
    "",
    "Each prompt accepts an optional `task` argument that is appended to the prompt text.",
    "",
    "## Resources",
    "",
    `- ${code(`decree://${name}/harness.json`)}: JSON summary of the harness (tools, subagents, guardrails).`,
    "",
    "## Environment",
    "",
    "| Variable | Required | Secret | Default | Description |",
    "|---|---|---|---|---|",
    ...envRows,
    "",
    "## Guardrails",
    "",
    `- Shell commands containing any blocked pattern are refused: ${
      g.blockedCommands.length > 0 ? g.blockedCommands.map(code).join(", ") : "(none configured)"
    }.`,
    `- File tools are confined to their root and to the allowed paths ${
      g.allowedPaths.length > 0 ? g.allowedPaths.map(code).join(", ") : "(none configured: every file access is refused)"
    }, relative to ${code(ROOT_ENV)}. Symlinks that escape are refused.`,
    `- Values of ${g.redactEnv.length > 0 ? g.redactEnv.map(code).join(", ") : "(no variables configured)"} are replaced with \`[REDACTED:NAME]\` in tool output.`,
    `- Set ${code(`${READ_ONLY_ENV}=1`)} to register only read-only tools.`,
    "- The server logs to stderr only; stdout carries the MCP protocol.",
    "",
  ];
  return lines.join("\n");
}
