import type { McpModel } from "../model.js";
import { isIdempotent, needsApproval, titleFromName, toolDescription } from "../model.js";
import { lit } from "../zod.js";

/** src/harness.ts: prompts and the spec summary resource. */
export function harnessTs(m: McpModel): string {
  const s = m.spec;
  const summary = {
    name: s.name,
    displayName: s.displayName,
    description: s.description,
    goal: s.goal,
    model: s.model,
    tools: m.tools.map((t) => ({
      name: t.name,
      kind: t.kind,
      description: t.description,
      readOnly: t.readOnly,
      destructive: t.destructive,
      requiresApproval: needsApproval(s, t),
      ...(t.source !== undefined ? { source: t.source } : {}),
    })),
    notExposed: m.skipped.map((t) => ({ name: t.name, kind: t.kind })),
    subagents: s.subagents.map((a) => ({ name: a.name, description: a.description, tools: a.tools })),
    prompts: m.prompts.map((p) => p.name),
    guardrails: s.guardrails,
    generatedBy: `decree-harness ${m.decreeVersion}`,
  };
  const prompts = m.prompts
    .map(
      (p) => `  {
    name: ${lit(p.name)},
    title: ${lit(p.title)},
    description: ${lit(p.description)},
    text: ${lit(p.text)},
    tools: ${lit(p.tools)},
  },`,
    )
    .join("\n");

  return String.raw`// Generated by decree-harness ${m.decreeVersion}. Prompts and harness metadata exposed over MCP.

export interface HarnessPrompt {
  name: string;
  title: string;
  description: string;
  /** System prompt text. */
  text: string;
  /** Tools on this server the prompt is meant to use. */
  tools: string[];
}

export const PROMPTS: HarnessPrompt[] = [
${prompts}
];

/** Render a prompt as the text of a single user message (MCP prompts have no system role). */
export function renderPrompt(p: HarnessPrompt, task?: string): string {
  let text = p.text.trim();
  if (p.tools.length > 0) {
    text +=
      "\n\n---\nTools available from the " +
      ${lit(m.serverName)} +
      " MCP server (your client may prefix their names): " +
      p.tools.join(", ") +
      ".";
  }
  if (task && task.trim()) text += "\n\n# Task\n" + task.trim();
  return text;
}

export const HARNESS_URI = ${lit(`decree://${m.serverName}/harness.json`)};

export const HARNESS_SUMMARY = ${lit(JSON.stringify(summary, null, 2))};
`;
}

export function serverTs(m: McpModel): string {
  const s = m.spec;
  const registrations = m.tools
    .map((t) => {
      const title = titleFromName(t.name);
      const reg = `server.registerTool(
  ${lit(t.name)},
  {
    title: ${lit(title)},
    description: ${lit(toolDescription(s, t))},
    inputSchema: INPUT_SCHEMAS[${lit(t.name)}],
    annotations: {
      title: ${lit(title)},
      readOnlyHint: ${t.readOnly},
      destructiveHint: ${t.destructive},
      idempotentHint: ${isIdempotent(t)},
      openWorldHint: ${t.kind === "http"},
    },
  },
  async (args) => runTool(${lit(t.name)}, args),
);`;
      if (t.readOnly) return reg;
      return `if (!READ_ONLY_MODE) {\n  ${reg.split("\n").join("\n  ")}\n}`;
    })
    .join("\n\n");

  return String.raw`#!/usr/bin/env node
// Generated by decree-harness ${m.decreeVersion}.
// MCP server (stdio) exposing this project's harness tools and prompts.
// stdout is the MCP protocol channel: log to stderr only (see log() in config.ts).
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { ErrorCode, GetPromptRequestSchema, McpError, type GetPromptResult } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
import { PROJECT_ROOT, READ_ONLY_MODE, SERVER_NAME, SERVER_VERSION, log } from "./config.js";
import { HARNESS_SUMMARY, HARNESS_URI, PROMPTS, renderPrompt, type HarnessPrompt } from "./harness.js";
import { INPUT_SCHEMAS, runTool } from "./tools.js";

const server = new McpServer(
  { name: SERVER_NAME, title: ${lit(s.displayName)}, version: SERVER_VERSION },
  { instructions: ${lit(`${s.description}\n\nTools operate on the project checkout on the machine running this server. Use the "${m.prompts[0]!.name}" prompt for the full agent system prompt.`)} },
);

// ---------------------------------------------------------------------------
// Tools
// ---------------------------------------------------------------------------

${registrations || "// (this harness has no client-executable tools)"}

// ---------------------------------------------------------------------------
// Prompts: the agent system prompt and one per subagent
// ---------------------------------------------------------------------------

for (const p of PROMPTS) {
  server.registerPrompt(
    p.name,
    {
      title: p.title,
      description: p.description,
      argsSchema: { task: z.string().optional().describe("Optional task to append to the prompt") },
    },
    ({ task }) => promptResult(p, task),
  );
}

function promptResult(p: HarnessPrompt, task?: string): GetPromptResult {
  return {
    description: p.description,
    messages: [{ role: "user", content: { type: "text", text: renderPrompt(p, task) } }],
  };
}

// The SDK rejects prompts/get without an "arguments" object when a prompt declares
// arguments, but "task" is optional and some clients omit "arguments" entirely.
// Serve prompts/get directly so both forms work.
server.server.setRequestHandler(GetPromptRequestSchema, async (request) => {
  const p = PROMPTS.find((x) => x.name === request.params.name);
  if (!p) throw new McpError(ErrorCode.InvalidParams, "Prompt " + request.params.name + " not found");
  const task = request.params.arguments?.task;
  if (task !== undefined && typeof task !== "string") {
    throw new McpError(ErrorCode.InvalidParams, "Prompt argument \"task\" must be a string");
  }
  return promptResult(p, task);
});

// ---------------------------------------------------------------------------
// Resources
// ---------------------------------------------------------------------------

server.registerResource(
  "harness",
  HARNESS_URI,
  {
    title: "Harness summary",
    description: "The decree harness spec summary: tools, subagents, guardrails.",
    mimeType: "application/json",
  },
  async (uri) => ({ contents: [{ uri: uri.href, mimeType: "application/json", text: HARNESS_SUMMARY }] }),
);

// ---------------------------------------------------------------------------
// Start
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  log("ready on stdio; project root:", PROJECT_ROOT, READ_ONLY_MODE ? "(read-only mode)" : "");
}

main().catch((err) => {
  log("fatal:", err instanceof Error ? err.stack ?? err.message : err);
  process.exit(1);
});
`;
}
