import type { ToolSpec } from "../../../core/types.js";
import type { McpModel } from "../model.js";
import { lit, toolInputZod } from "../zod.js";

/** The binding data the runtime needs for one tool (no descriptions / schemas). */
function binding(t: ToolSpec): Record<string, unknown> {
  const b: Record<string, unknown> = { kind: t.kind };
  if (t.kind === "http" && t.http) {
    const h = t.http;
    const http: Record<string, unknown> = { method: h.method, baseUrlEnv: h.baseUrlEnv, path: h.path };
    if (h.defaultBaseUrl !== undefined) http.defaultBaseUrl = h.defaultBaseUrl;
    if (h.queryParams?.length) http.queryParams = h.queryParams;
    if (h.headerParams?.length) http.headerParams = h.headerParams;
    if (h.bodyParam !== undefined) http.bodyParam = h.bodyParam;
    if (h.auth) {
      const a: Record<string, unknown> = { type: h.auth.type };
      if (h.auth.env !== undefined) a.env = h.auth.env;
      if (h.auth.header !== undefined) a.header = h.auth.header;
      http.auth = a;
    }
    b.http = http;
  }
  if (t.kind === "shell" && t.shell) {
    const s: Record<string, unknown> = { command: t.shell.command };
    if (t.shell.cwd !== undefined) s.cwd = t.shell.cwd;
    if (t.shell.timeoutMs !== undefined) s.timeoutMs = t.shell.timeoutMs;
    const props = t.inputSchema?.properties ?? {};
    const allowFlags = Object.keys(props).filter((k) => (props[k] as Record<string, unknown> | undefined)?.["x-allow-flags"] === true);
    if (allowFlags.length) s.allowFlags = allowFlags;
    b.shell = s;
  }
  if (["read_file", "write_file", "list_files", "search"].includes(t.kind)) {
    const f: Record<string, unknown> = { root: t.fs?.root ?? "." };
    if (t.fs?.maxBytes !== undefined) f.maxBytes = t.fs.maxBytes;
    b.fs = f;
  }
  return b;
}

function indentJson(value: unknown, indent: string): string {
  return JSON.stringify(value, null, 2)
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029")
    .split("\n")
    .join(`\n${indent}`);
}

export function toolsTs(m: McpModel): string {
  const schemas = m.tools.map((t) => `  ${lit(t.name)}: ${toolInputZod(t.inputSchema ?? {}, "  ")},`).join("\n");
  const bindings = m.tools.map((t) => `  ${lit(t.name)}: ${indentJson(binding(t), "  ")},`).join("\n");

  return String.raw`// Generated by decree-harness ${m.decreeVersion}. Tool implementations for the MCP server.
// Semantics match the decree runtime (docs: "Tool semantics"): http, shell, read_file,
// write_file, list_files, search. Guardrails: blockedCommands, allowedPaths, redactEnv.
import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { z } from "zod";
import { GUARDRAILS, PROJECT_ROOT } from "./config.js";

// ---------------------------------------------------------------------------
// Input schemas (generated from each tool's JSON Schema)
// ---------------------------------------------------------------------------

export const INPUT_SCHEMAS = {
${schemas}
};

// ---------------------------------------------------------------------------
// Bindings
// ---------------------------------------------------------------------------

type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS";

export interface ToolBinding {
  kind: "http" | "shell" | "read_file" | "write_file" | "list_files" | "search";
  http?: {
    method: HttpMethod;
    baseUrlEnv: string;
    defaultBaseUrl?: string;
    path: string;
    queryParams?: string[];
    headerParams?: string[];
    bodyParam?: string;
    auth?: { type: "bearer" | "header" | "none"; env?: string; header?: string };
  };
  /** allowFlags: params whose values may start with "-" (schema "x-allow-flags": true). */
  shell?: { command: string; cwd?: string; timeoutMs?: number; allowFlags?: string[] };
  fs?: { root: string; maxBytes?: number };
}

export const TOOLS: Record<string, ToolBinding> = {
${bindings}
};

export interface ToolResult {
  [key: string]: unknown;
  content: { type: "text"; text: string }[];
  isError?: boolean;
}

type Input = Record<string, unknown>;

// ---------------------------------------------------------------------------
// Output hygiene
// ---------------------------------------------------------------------------

/**
 * Replace the value of every env var in guardrails.redactEnv with [REDACTED:NAME]
 * (values shorter than 4 chars are ignored). Tools also call it before truncating,
 * so a cut never leaves part of a secret behind.
 */
export function redact(text: string): string {
  const pairs = GUARDRAILS.redactEnv
    .map((name) => [name, process.env[name] ?? ""] as const)
    .filter(([, value]) => value.length >= 4)
    .sort((a, b) => b[1].length - a[1].length);
  let out = text;
  for (const [name, value] of pairs) out = out.split(value).join("[REDACTED:" + name + "]");
  return out;
}

function result(text: string, isError = false): ToolResult {
  return { content: [{ type: "text", text: redact(text) }], ...(isError ? { isError: true } : {}) };
}

/** Own-property lookup: a param named "constructor" must not read Object.prototype. */
function get(input: Input, key: string): unknown {
  return Object.hasOwn(input, key) ? input[key] : undefined;
}

function asText(v: unknown): string {
  if (typeof v === "string") return v;
  if (v === undefined || v === null) return "";
  if (typeof v === "object") return JSON.stringify(v);
  return String(v);
}

// ---------------------------------------------------------------------------
// Dispatcher
// ---------------------------------------------------------------------------

export async function runTool(name: string, input: Input): Promise<ToolResult> {
  const tool = TOOLS[name];
  if (!tool) return result("Unknown tool: " + name, true);
  try {
    switch (tool.kind) {
      case "http":
        return await runHttp(tool, input);
      case "shell":
        return await runShell(tool, input);
      case "read_file":
        return readFileTool(tool, input);
      case "write_file":
        return writeFileTool(tool, input);
      case "list_files":
        return listFilesTool(tool, input);
      case "search":
        return searchTool(tool, input);
    }
  } catch (err) {
    return result("Error: " + (err instanceof Error ? err.message : String(err)), true);
  }
}

// ---------------------------------------------------------------------------
// http
// ---------------------------------------------------------------------------

const HTTP_MAX_CHARS = 50_000;
const HTTP_TIMEOUT_MS = 60_000;
/** Same-origin redirects followed per request; cross-origin redirects are never followed. */
const HTTP_MAX_REDIRECTS = 5;

async function runHttp(tool: ToolBinding, input: Input): Promise<ToolResult> {
  const h = tool.http!;
  const base = process.env[h.baseUrlEnv] || h.defaultBaseUrl;
  if (!base) return result("Missing base URL: set " + h.baseUrlEnv, true);

  const consumed = new Set<string>();
  let missing: string | null = null;
  let dotSegment: string | null = null;
  const urlPath = h.path.replace(/\{([^}]+)\}/g, (_m, key: string) => {
    consumed.add(key);
    const v = get(input, key);
    if (v === undefined || v === null) {
      missing = key;
      return "";
    }
    // "." and ".." would be resolved as dot segments by the URL parser (/users/.. -> /).
    if (asText(v) === "." || asText(v) === "..") dotSegment = key;
    return encodeURIComponent(asText(v));
  });
  if (missing) return result("Missing required path parameter: " + missing, true);
  if (dotSegment) return result("Path parameter " + dotSegment + ' may not be "." or "..".', true);

  const url = new URL(base.replace(/\/+$/, "") + urlPath);
  for (const key of h.queryParams ?? []) {
    consumed.add(key);
    const v = get(input, key);
    if (v === undefined || v === null) continue;
    if (Array.isArray(v)) for (const item of v) url.searchParams.append(key, asText(item));
    else url.searchParams.set(key, asText(v));
  }

  const headers: Record<string, string> = { accept: "application/json, text/plain;q=0.9, */*;q=0.8" };
  for (const key of h.headerParams ?? []) {
    consumed.add(key);
    const v = get(input, key);
    if (v !== undefined && v !== null) headers[key] = asText(v);
  }
  const auth = h.auth;
  if (auth && auth.type !== "none" && auth.env) {
    const secret = process.env[auth.env];
    if (secret) {
      if (auth.type === "bearer") headers["authorization"] = "Bearer " + secret;
      else if (auth.type === "header" && auth.header) headers[auth.header] = secret;
    }
  }

  let body: string | undefined;
  if (["POST", "PUT", "PATCH", "DELETE"].includes(h.method)) {
    let payload: unknown;
    if (h.bodyParam) {
      payload = get(input, h.bodyParam);
    } else {
      const rest: Input = {};
      for (const [k, v] of Object.entries(input)) if (!consumed.has(k) && v !== undefined) rest[k] = v;
      payload = Object.keys(rest).length > 0 ? rest : undefined;
    }
    if (payload !== undefined) {
      body = JSON.stringify(payload);
      headers["content-type"] = "application/json";
    }
  }

  let res: Response;
  let note: string | undefined;
  try {
    ({ res, note } = await fetchSameOrigin(url, { method: h.method, headers, body, signal: AbortSignal.timeout(HTTP_TIMEOUT_MS) }));
  } catch (err) {
    const msg = err instanceof Error ? (err.name === "TimeoutError" ? "timed out after 60s" : err.message) : String(err);
    return result("HTTP request failed: " + h.method + " " + url.toString() + ": " + msg, true);
  }
  // Redact before truncating: a cut through a secret would leave a piece redact() cannot match.
  let text = redact(await res.text());
  if (text.length > HTTP_MAX_CHARS) {
    const extra = text.length - HTTP_MAX_CHARS;
    text = text.slice(0, HTTP_MAX_CHARS) + "\n…[truncated " + extra + " chars]";
  }
  return result("HTTP " + res.status + " " + res.statusText + "\n" + (note ? note + "\n" : "") + text, res.status >= 400);
}

/**
 * fetch with redirect: "manual", following at most HTTP_MAX_REDIRECTS redirects that stay
 * on the same origin. A redirect to another origin is returned as-is with a note, so the
 * auth header never leaves the API's origin. 303 (and 301/302 after POST) continue as GET.
 */
async function fetchSameOrigin(
  start: URL,
  init: { method: string; headers: Record<string, string>; body?: string; signal: AbortSignal },
): Promise<{ res: Response; note?: string }> {
  let url = start;
  let { method, body } = init;
  const headers = { ...init.headers };
  for (let hop = 0; ; hop++) {
    const res = await fetch(url, { method, headers, body, signal: init.signal, redirect: "manual" });
    const location = res.headers.get("location");
    if (res.status < 300 || res.status >= 400 || res.status === 304 || !location) return { res };
    let next: URL;
    try {
      next = new URL(location, url);
    } catch {
      return { res, note: "[redirect not followed: invalid Location " + JSON.stringify(location) + "]" };
    }
    if (next.origin !== url.origin) return { res, note: "[redirect to " + next.href + " not followed: different origin]" };
    if (hop >= HTTP_MAX_REDIRECTS) return { res, note: "[redirect not followed: more than " + HTTP_MAX_REDIRECTS + " redirects]" };
    await res.body?.cancel().catch(() => undefined);
    if (res.status === 303 || ((res.status === 301 || res.status === 302) && method === "POST")) {
      if (method !== "HEAD") method = "GET";
      body = undefined;
      delete headers["content-type"];
    }
    url = next;
  }
}

// ---------------------------------------------------------------------------
// shell
// ---------------------------------------------------------------------------

const SHELL_MAX_CHARS = 30_000;

/** POSIX single-quote escaping. */
export function shellQuote(value: string): string {
  return "'" + value.replace(/'/g, "'\\''") + "'";
}

const PLACEHOLDER_AT = /^\{\{\s*([A-Za-z0-9_-]+)\s*\}\}/;

/**
 * A quoted value is one literal shell word only where the placeholder is plain,
 * top-level shell text. Returns why a placeholder is not (inside quotes, backticks,
 * a parameter expansion or a comment; right after a dollar sign, a backslash or
 * "$("), or null when the template is safe.
 */
export function unsafePlaceholder(template: string): string | null {
  const stack: string[] = [];
  const startsPlaceholder = (j: number) => PLACEHOLDER_AT.test(template.slice(j));
  const BACKTICK = String.fromCharCode(96);
  for (let i = 0; i < template.length; ) {
    const match = PLACEHOLDER_AT.exec(template.slice(i));
    if (match) {
      if (stack.length > 0) return "{{" + match[1] + "}} is inside " + stack[stack.length - 1];
      if (template[i - 1] === "$" || template[i - 1] === "\\" || /\$\(\s*$/.test(template.slice(0, i))) {
        return "{{" + match[1] + "}} follows a dollar sign, a backslash or $(";
      }
      i += match[0].length;
      continue;
    }
    const c = template[i]!;
    const top = stack[stack.length - 1];
    if (top === "single quotes" || top === "a comment") {
      if (c === (top === "a comment" ? "\n" : "'")) stack.pop();
      i++;
      continue;
    }
    if (c === "\\") {
      i += startsPlaceholder(i + 1) ? 1 : 2;
      continue;
    }
    const expansion = c === "$" && template[i + 1] === "{" && !startsPlaceholder(i + 1);
    if (top === "double quotes") {
      if (c === '"') stack.pop();
      else if (c === BACKTICK) stack.push("backticks");
      else if (expansion) stack.push("a parameter expansion");
    } else if (c === "'") stack.push("single quotes");
    else if (c === '"') stack.push("double quotes");
    else if (c === BACKTICK) {
      if (top === "backticks") stack.pop();
      else stack.push("backticks");
    } else if (expansion) stack.push("a parameter expansion");
    else if (c === "}" && top === "a parameter expansion") stack.pop();
    else if (c === "#" && (i === 0 || /[\s;&|()<>]/.test(template[i - 1]!))) stack.push("a comment");
    i += expansion ? 2 : 1;
  }
  return null;
}

/**
 * Fill {{param}} placeholders with quoted values; missing params become "" and spaces collapse.
 * Throws when the template is unsafe, or when a value starts with "-" (it would be read
 * as an option) and the param is not in allowFlags.
 */
export function renderCommand(template: string, input: Input, allowFlags: string[] = []): string {
  const unsafe = unsafePlaceholder(template);
  if (unsafe) throw new Error("unsafe command template: " + unsafe + "; placeholders must be bare shell words.");
  const values: string[] = [];
  const marked = template.replace(/\{\{\s*([A-Za-z0-9_-]+)\s*\}\}/g, (_m, key: string) => {
    const v = get(input, key);
    if (v === undefined || v === null) return "";
    const text = asText(v);
    if (text.startsWith("-") && !allowFlags.includes(key)) throw new Error("parameter values may not start with '-' (" + key + ").");
    values.push(shellQuote(text));
    return "\u0000" + (values.length - 1) + "\u0000";
  });
  return marked
    .replace(/ {2,}/g, " ")
    .trim()
    .replace(/\u0000(\d+)\u0000/g, (_m, i: string) => values[Number(i)]!);
}

function runShell(tool: ToolBinding, input: Input): Promise<ToolResult> {
  const s = tool.shell!;
  let command: string;
  try {
    command = renderCommand(s.command, input, s.allowFlags);
  } catch (err) {
    return Promise.resolve(result("Refused: " + (err instanceof Error ? err.message : String(err)), true));
  }
  const blocked = GUARDRAILS.blockedCommands.find((b) => b.length > 0 && command.includes(b));
  if (blocked !== undefined) {
    return Promise.resolve(result("Refused: the command contains a blocked pattern (" + blocked + ").", true));
  }
  const cwd = path.resolve(PROJECT_ROOT, s.cwd ?? ".");
  const timeoutMs = s.timeoutMs ?? 120_000;

  return new Promise((resolve) => {
    let out = "";
    let dropped = 0;
    const append = (chunk: Buffer) => {
      out += chunk.toString("utf8");
      if (out.length > SHELL_MAX_CHARS * 2) {
        // Redact before cutting: a cut through a secret would leave a piece redact() cannot match.
        out = redact(out);
        if (out.length > SHELL_MAX_CHARS) {
          dropped += out.length - SHELL_MAX_CHARS;
          out = out.slice(out.length - SHELL_MAX_CHARS);
        }
      }
    };
    // stdin is ignored: the server's own stdin is the MCP protocol channel.
    const child = spawn("/bin/sh", ["-c", command], {
      cwd,
      env: process.env,
      stdio: ["ignore", "pipe", "pipe"],
      detached: process.platform !== "win32",
    });
    let timedOut = false;
    const timer = setTimeout(() => {
      timedOut = true;
      try {
        if (child.pid !== undefined && process.platform !== "win32") process.kill(-child.pid, "SIGKILL");
        else child.kill("SIGKILL");
      } catch {
        child.kill("SIGKILL");
      }
    }, timeoutMs);
    child.stdout!.on("data", append);
    child.stderr!.on("data", append);
    child.on("error", (err) => {
      clearTimeout(timer);
      resolve(result("Failed to start command: " + err.message, true));
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      out = redact(out);
      if (out.length > SHELL_MAX_CHARS) {
        dropped += out.length - SHELL_MAX_CHARS;
        out = out.slice(out.length - SHELL_MAX_CHARS);
      }
      const body = (dropped > 0 ? "…[truncated " + dropped + " chars]\n" : "") + out;
      if (timedOut) {
        resolve(result("exit code: 124\n" + body + "\n[timed out after " + timeoutMs + "ms]", true));
        return;
      }
      const exit = code ?? 1;
      resolve(result("exit code: " + exit + "\n" + body, exit !== 0));
    });
  });
}

// ---------------------------------------------------------------------------
// Filesystem guardrails
// ---------------------------------------------------------------------------

function within(parent: string, child: string): boolean {
  const rel = path.relative(parent, child);
  return rel === "" || (!rel.startsWith("..") && !path.isAbsolute(rel));
}

/** realpath of the path, or of its nearest existing ancestor joined with the rest. */
function realish(p: string): string {
  let cur = p;
  const rest: string[] = [];
  for (;;) {
    try {
      return path.join(fs.realpathSync(cur), ...rest.reverse());
    } catch {
      // It exists but cannot be resolved (a dangling or looping symlink): a write through
      // it could land anywhere, so refuse instead of trusting the lexical path.
      let exists = false;
      try {
        fs.lstatSync(cur);
        exists = true;
      } catch {
        exists = false;
      }
      if (exists) throw new Error("Path goes through a symlink that cannot be resolved: " + p);
      const parent = path.dirname(cur);
      if (parent === cur) return p;
      rest.push(path.basename(cur));
      cur = parent;
    }
  }
}

function fsRoot(tool: ToolBinding): string {
  return path.resolve(PROJECT_ROOT, tool.fs?.root ?? ".");
}

/** Resolve a user-supplied path against the tool's root; throw if it escapes or is not allowed. */
export function resolveSafe(tool: ToolBinding, p: string): string {
  const root = fsRoot(tool);
  const abs = path.resolve(root, p || ".");
  if (!within(root, abs) || !within(realish(root), realish(abs))) {
    throw new Error("Path escapes the allowed root: " + p);
  }
  if (!isAllowed(abs)) throw new Error("Path is outside guardrails.allowedPaths: " + p);
  return abs;
}

/** Root of a walking tool (list_files/search): must stay inside the project; entries are filtered individually. */
function walkRoot(tool: ToolBinding): string {
  const root = fsRoot(tool);
  if (!within(PROJECT_ROOT, root) || !within(realish(PROJECT_ROOT), realish(root))) {
    throw new Error("Tool root escapes the project root: " + (tool.fs?.root ?? "."));
  }
  return root;
}

function isAllowed(abs: string): boolean {
  const real = realish(abs);
  return GUARDRAILS.allowedPaths.some((a) => {
    const allowed = path.resolve(PROJECT_ROOT, a);
    return within(allowed, abs) && within(realish(allowed), real);
  });
}

/** For entries found by walking: no symlink may lead outside the root or the allowed paths. */
function safeChild(root: string, abs: string): boolean {
  try {
    return within(realish(root), realish(abs)) && isAllowed(abs);
  } catch {
    return false;
  }
}

function display(tool: ToolBinding, abs: string): string {
  return path.relative(fsRoot(tool), abs).split(path.sep).join("/") || ".";
}

// ---------------------------------------------------------------------------
// read_file / write_file
// ---------------------------------------------------------------------------

function readFileTool(tool: ToolBinding, input: Input): ToolResult {
  const abs = resolveSafe(tool, asText(input.path));
  const max = tool.fs?.maxBytes ?? 200_000;
  const stat = fs.statSync(abs);
  if (stat.isDirectory()) return result("Not a file (directory): " + display(tool, abs), true);
  const fd = fs.openSync(abs, "r");
  try {
    const buf = Buffer.alloc(Math.min(stat.size, max));
    const n = fs.readSync(fd, buf, 0, buf.length, 0);
    let text = buf.subarray(0, n).toString("utf8");
    if (stat.size > max) text += "\n…[truncated " + (stat.size - max) + " bytes]";
    return result(text);
  } finally {
    fs.closeSync(fd);
  }
}

function writeFileTool(tool: ToolBinding, input: Input): ToolResult {
  const abs = resolveSafe(tool, asText(input.path));
  const content = asText(input.content);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content, "utf8");
  return result("wrote " + Buffer.byteLength(content, "utf8") + " bytes to " + display(tool, abs));
}

// ---------------------------------------------------------------------------
// list_files / search
// ---------------------------------------------------------------------------

const IGNORED_DIRS = new Set(["node_modules", ".git", "dist", ".decree", ".venv", "venv", "__pycache__", ".next", ".nuxt", ".svelte-kit", ".turbo", ".tox", ".mypy_cache", ".pytest_cache", ".ruff_cache"]);
const MAX_WALK = 100_000;

/** Convert a glob (*, **, ?, [..], {a,b}) to an anchored RegExp over POSIX relative paths. */
export function globToRegExp(glob: string): RegExp {
  let re = "";
  let inGroup = 0;
  for (let i = 0; i < glob.length; i++) {
    const c = glob[i]!;
    if (c === "*") {
      if (glob[i + 1] === "*") {
        const atStart = i === 0 || glob[i - 1] === "/";
        const atEnd = i + 2 === glob.length || glob[i + 2] === "/";
        if (atStart && atEnd) {
          i += 2; // consume "**" and a trailing "/"
          re += i >= glob.length ? ".*" : "(?:.*/)?";
          continue;
        }
        i++;
        re += "[^/]*";
        continue;
      }
      re += "[^/]*";
    } else if (c === "?") {
      re += "[^/]";
    } else if (c === "[") {
      const end = glob.indexOf("]", i + 1);
      if (end === -1) {
        re += "\\[";
      } else {
        let cls = glob.slice(i + 1, end).replace(/\\/g, "\\\\");
        if (cls.startsWith("!")) cls = "^" + cls.slice(1);
        re += "[" + cls + "]";
        i = end;
      }
    } else if (c === "{") {
      inGroup++;
      re += "(?:";
    } else if (c === "}" && inGroup > 0) {
      inGroup--;
      re += ")";
    } else if (c === "," && inGroup > 0) {
      re += "|";
    } else if (c === "\\" && i + 1 < glob.length) {
      i++;
      re += glob[i]!.replace(/[.*+?^$()|[\]\\{}]/g, "\\$&");
    } else {
      re += c.replace(/[.*+?^$()|[\]\\{}/]/g, "\\$&");
    }
  }
  return new RegExp("^" + re + "$");
}

/** Walk files under dir (sorted, POSIX relative paths), skipping ignored dirs and symlinked dirs. */
function walk(dir: string): string[] {
  const out: string[] = [];
  const stack: string[] = [""];
  while (stack.length > 0 && out.length < MAX_WALK) {
    const rel = stack.pop()!;
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(path.join(dir, rel), { withFileTypes: true });
    } catch {
      continue;
    }
    entries.sort((a, b) => (a.name < b.name ? 1 : a.name > b.name ? -1 : 0));
    for (const e of entries) {
      const child = rel ? rel + "/" + e.name : e.name;
      if (e.isDirectory()) {
        if (!IGNORED_DIRS.has(e.name)) stack.push(child);
      } else if (e.isFile() || e.isSymbolicLink()) {
        out.push(child);
      }
    }
  }
  return out.sort();
}

function listFilesTool(tool: ToolBinding, input: Input): ToolResult {
  const root = walkRoot(tool);
  const pattern = asText(input.pattern).replace(/^\.\//, "") || "**/*";
  const re = globToRegExp(pattern);
  const matches: string[] = [];
  let total = 0;
  for (const rel of walk(root)) {
    if (!re.test(rel)) continue;
    if (!safeChild(root, path.join(root, rel))) continue;
    total++;
    if (matches.length < 500) matches.push(rel);
  }
  if (matches.length === 0) return result("no files match " + pattern);
  const more = total > matches.length ? "\n…[" + (total - matches.length) + " more files not shown]" : "";
  return result(matches.join("\n") + more);
}

const SEARCH_MAX_MATCHES = 200;
const SEARCH_MAX_FILE_BYTES = 1_000_000;

function searchTool(tool: ToolBinding, input: Input): ToolResult {
  const root = walkRoot(tool);
  let re: RegExp;
  try {
    re = new RegExp(asText(input.query));
  } catch (err) {
    return result("Invalid regular expression: " + (err instanceof Error ? err.message : String(err)), true);
  }
  const glob = asText(input.glob).replace(/^\.\//, "");
  // Like ripgrep's -g: a glob without "/" matches the file name at any depth.
  const globRe = glob ? globToRegExp(glob.includes("/") ? glob : "**/" + glob) : null;
  const matches: string[] = [];
  let truncated = false;
  outer: for (const rel of walk(root)) {
    if (globRe && !globRe.test(rel)) continue;
    const abs = path.join(root, rel);
    if (!safeChild(root, abs)) continue;
    let buf: Buffer;
    try {
      const st = fs.statSync(abs);
      if (!st.isFile() || st.size > SEARCH_MAX_FILE_BYTES) continue;
      buf = fs.readFileSync(abs);
    } catch {
      continue;
    }
    if (buf.subarray(0, 8000).includes(0)) continue; // binary
    const lines = buf.toString("utf8").split(/\r?\n/);
    for (let i = 0; i < lines.length; i++) {
      re.lastIndex = 0;
      if (!re.test(lines[i]!)) continue;
      if (matches.length >= SEARCH_MAX_MATCHES) {
        truncated = true;
        break outer;
      }
      const line = lines[i]!.length > 500 ? lines[i]!.slice(0, 500) + "…" : lines[i]!;
      matches.push(rel + ":" + (i + 1) + ": " + line);
    }
  }
  if (matches.length === 0) return result("no matches");
  return result(matches.join("\n") + (truncated ? "\n…[stopped at " + SEARCH_MAX_MATCHES + " matches]" : ""));
}
`;
}
