import type { GeneratedFile, GenerateOptions, HarnessSpec } from "../../core/types.js";
import { buildModel, isFsKind } from "./model.js";
import { agentTs, subagentsTs } from "./templates/agent.js";
import { cliTs } from "./templates/cli.js";
import { configTs, promptTs } from "./templates/config.js";
import { clientTs, sessionTs, typesTs, validateTs } from "./templates/core.js";
import { evalsTs } from "./templates/evals.js";
import { loopTs } from "./templates/loop.js";
import { envExample, gitignore, packageJson, tsconfigJson } from "./templates/project.js";
import { readmeMd } from "./templates/readme.js";
import { fsTs, httpTs, memoryTs, shellTs } from "./templates/tool-helpers.js";
import { toolsIndexTs } from "./templates/tools-index.js";
import { decisionsJson, decisionsModuleTs } from "../common/decisions.js";

/**
 * Render the standalone TypeScript harness: a small npm package with an agent
 * loop on the Anthropic SDK, the spec's tools, subagents, a CLI and evals.
 * Pure and deterministic: the same spec always yields byte-identical files.
 */
export function generateTypescript(spec: HarnessSpec, opts: GenerateOptions): GeneratedFile[] {
  const m = buildModel(spec, opts);
  const header = `// Generated by decree-harness ${opts.decreeVersion} from decree.json. Yours to edit.\n`;
  const ts = (path: string, content: string): GeneratedFile => ({ path, content: header + content });

  const files: GeneratedFile[] = [
    { path: "package.json", content: packageJson(m) },
    { path: "tsconfig.json", content: tsconfigJson() },
    { path: "README.md", content: readmeMd(m) },
    { path: ".env.example", content: envExample(m) },
    { path: ".gitignore", content: gitignore() },
    ts("src/config.ts", configTs(m)),
    ts("src/prompt.ts", promptTs(m)),
    ts("src/types.ts", typesTs()),
    ts("src/session.ts", sessionTs()),
    ts("src/client.ts", clientTs()),
    ts("src/validate.ts", validateTs()),
    ts("src/loop.ts", loopTs()),
    ts("src/agent.ts", agentTs(m)),
    ts("src/cli.ts", cliTs(m)),
    ts("src/evals.ts", evalsTs(m)),
    ts("src/tools/index.ts", toolsIndexTs(m)),
  ];

  const kinds = [...m.kinds];
  const needsHttp = m.tools.some((t) => t.spec.kind === "http" && t.spec.http);
  const needsShell = m.tools.some((t) => t.spec.kind === "shell" && t.spec.shell);
  if (needsHttp) files.push(ts("src/tools/http.ts", httpTs()));
  if (needsShell) files.push(ts("src/tools/shell.ts", shellTs()));
  if (kinds.some(isFsKind)) files.push(ts("src/tools/fs.ts", fsTs()));
  if (m.kinds.has("memory")) files.push(ts("src/tools/memory.ts", memoryTs()));
  if (m.kinds.has("decisions")) {
    files.push(ts("src/tools/decisions.ts", decisionsModuleTs("../config.js")));
    files.push({ path: "decisions.json", content: decisionsJson(spec) });
  }
  if (m.subagents.length > 0) files.push(ts("src/subagents.ts", subagentsTs(m)));

  return files;
}
