/**
 * Marker file decree writes at the root of every generated output directory (`agent/` by default). The built-in
 * runtime's and every generated target's `list_files` / `search`, and the project scanner, skip any directory
 * that contains it, so the agent's own file tools never wander into the generated harness.
 */
export const GENERATED_MARKER = ".decree-generated";

export const GENERATED_MARKER_CONTENT =
  "This directory was generated by decree-harness from decree.json.\n" +
  "While this file exists, decree's file tools (list_files, search) and project scanner skip this directory.\n";
