import type { PyContext } from "../context.js";
import { plain, pyStr, pyStrTuple, pyText } from "../py.js";

/** Module docstring shared by every generated module. Only `plain()` text goes inside. */
export function docstring(ctx: PyContext, summary: string): string {
  return `"""${summary}

Part of the ${plain(ctx.spec.displayName, 80) || ctx.pkg} agent harness, generated by
decree-harness ${plain(ctx.opts.decreeVersion, 40)}. Safe to edit.
"""`;
}

function pyFloat(n: number): string {
  return Number.isInteger(n) ? `${n}.0` : String(n);
}

export function configPy(ctx: PyContext): string {
  const { spec } = ctx;
  const g = spec.guardrails;
  const P = ctx.envPrefix;
  return String.raw`${docstring(ctx, "Runtime configuration: model, guardrails, context strategy, limits and pricing.")}

from __future__ import annotations

import os
from pathlib import Path

NAME = ${pyStr(spec.name)}
DISPLAY_NAME = ${pyStr(spec.displayName)}
DESCRIPTION = ${pyText(spec.description)}

# --------------------------------------------------------------------------
# Model
# --------------------------------------------------------------------------

#: Main agent model. Override with ${P}_MODEL (or --model on the CLI).
MODEL: str = os.environ.get(${pyStr(P + "_MODEL")}) or ${pyStr(spec.model.id)}
#: Default model for subagents that do not pin their own.
SUBAGENT_MODEL: str = os.environ.get(${pyStr(P + "_SUBAGENT_MODEL")}) or ${pyStr(spec.model.subagentId)}
#: output_config.effort: "low" | "medium" | "high" | "xhigh" | "max".
EFFORT: str = ${pyStr(spec.model.effort)}
#: Send thinking={"type": "adaptive"} when True; omit the parameter otherwise.
ADAPTIVE_THINKING: bool = ${spec.model.thinking === "adaptive" ? "True" : "False"}

# --------------------------------------------------------------------------
# Guardrails
# --------------------------------------------------------------------------

#: Hard cap on model requests per run (tool round trips and pause_turn resumes count).
MAX_TURNS: int = ${Math.max(1, Math.floor(g.maxTurns))}
#: max_tokens for every request.
MAX_OUTPUT_TOKENS: int = ${Math.max(1, Math.floor(g.maxOutputTokensPerTurn))}
#: Stop once the estimated spend of the session passes this (None = no limit).
MAX_COST_USD: float | None = ${g.maxCostUsd === undefined || g.maxCostUsd === null ? "None" : pyFloat(g.maxCostUsd)}
#: Shell commands containing any of these substrings are refused.
BLOCKED_COMMANDS: tuple[str, ...] = ${pyStrTuple(g.blockedCommands)}
#: File tools may only touch paths under these roots (relative to the project root).
ALLOWED_PATHS: tuple[str, ...] = ${pyStrTuple(g.allowedPaths)}
#: Values of these environment variables are scrubbed from tool output.
REDACT_ENV: tuple[str, ...] = ${pyStrTuple(g.redactEnv)}
#: Who needs a human yes: "always" | "destructive" | "never".
APPROVAL_MODE: str = ${pyStr(g.approvalMode)}

# --------------------------------------------------------------------------
# Context strategy
# --------------------------------------------------------------------------

#: cache_control on the system prompt plus automatic caching of the conversation tail.
PROMPT_CACHING: bool = ${spec.context.caching ? "True" : "False"}
#: Server-side compaction (beta compact-2026-01-12) for long sessions.
COMPACTION: bool = ${spec.context.compaction ? "True" : "False"}
#: Clear old tool results (beta context-management-2025-06-27).
CONTEXT_EDITING: bool = ${spec.context.contextEditing ? "True" : "False"}

COMPACTION_BETA = "compact-2026-01-12"
CONTEXT_EDITING_BETA = "context-management-2025-06-27"

# --------------------------------------------------------------------------
# Paths
# --------------------------------------------------------------------------


def project_root() -> Path:
    """The codebase the tools operate on: ${P}_PROJECT_ROOT, else the current directory."""
    return Path(os.environ.get(${pyStr(P + "_PROJECT_ROOT")}) or os.getcwd()).resolve()


def memory_dir() -> Path:
    """Backing directory for the memory tool: ${P}_MEMORY_DIR, else ./memories."""
    return Path(os.environ.get(${pyStr(P + "_MEMORY_DIR")}) or "memories").resolve()


# --------------------------------------------------------------------------
# Tool limits (shared semantics with every decree-harness target)
# --------------------------------------------------------------------------

HTTP_TIMEOUT_S = 60.0
HTTP_MAX_BODY_CHARS = 50_000
SHELL_DEFAULT_TIMEOUT_MS = 120_000
SHELL_MAX_OUTPUT_CHARS = 30_000
FS_DEFAULT_MAX_BYTES = 200_000
LIST_MAX_RESULTS = 500
SEARCH_MAX_MATCHES = 200
SEARCH_MAX_FILE_BYTES = 1_000_000
IGNORED_DIRS = frozenset({"node_modules", ".git", "dist", ".decree"})
SERVER_TOOL_MAX_USES = 5

# --------------------------------------------------------------------------
# Pricing (USD per 1M tokens: input, output). Cache reads bill at 0.1x input,
# cache writes at 1.25x input. Longest matching prefix wins.
# --------------------------------------------------------------------------

PRICING: dict[str, tuple[float, float]] = {
    "claude-opus-5-5": (4.0, 20.0),
    "claude-opus-5": (5.0, 25.0),
    "claude-fable-5-1": (10.0, 50.0),
    "claude-fable-5": (10.0, 50.0),
    "claude-opus-4-8": (5.0, 25.0),
    "claude-opus-4-7": (5.0, 25.0),
    "claude-opus-4-6": (5.0, 25.0),
    "claude-sonnet-5": (2.0, 10.0),
    "claude-sonnet-4-6": (3.0, 15.0),
    "claude-haiku-4-5": (1.0, 5.0),
}
DEFAULT_PRICE: tuple[float, float] = (5.0, 25.0)


def price_for(model: str) -> tuple[float, float]:
    """(input, output) USD per 1M tokens for a model id."""
    for prefix in sorted(PRICING, key=len, reverse=True):
        if model == prefix or model.startswith(prefix + "-") or model.startswith(prefix + "["):
            return PRICING[prefix]
    return DEFAULT_PRICE


def estimate_cost_usd(
    model: str,
    input_tokens: int,
    output_tokens: int,
    cache_read_tokens: int = 0,
    cache_write_tokens: int = 0,
) -> float:
    """Estimated spend for one usage record."""
    price_in, price_out = price_for(model)
    return (
        input_tokens * price_in
        + output_tokens * price_out
        + cache_read_tokens * price_in * 0.1
        + cache_write_tokens * price_in * 1.25
    ) / 1_000_000
`;
}
