import type { PyContext } from "../context.js";
import { envValue, mdCell, plain, tomlStr } from "../py.js";
import { docstring } from "./config.js";
import { delegateToolName } from "../context.js";

export const ANTHROPIC_REQUIREMENT = "anthropic>=1.8";
export const HTTPX_REQUIREMENT = "httpx>=0.27";
export const PACKAGE_VERSION = "0.1.0";

export function initPy(ctx: PyContext): string {
  return `${docstring(ctx, plain(ctx.spec.displayName, 80) + " - an agent harness built on the Anthropic API.")}

__version__ = "${PACKAGE_VERSION}"

__all__ = ["__version__"]
`;
}

export function mainPy(ctx: PyContext): string {
  return `${docstring(ctx, "Entry point for python -m " + ctx.pkg + ".")}

import sys

from .cli import main

sys.exit(main())
`;
}

export function pyprojectToml(ctx: PyContext): string {
  const deps = [ANTHROPIC_REQUIREMENT, ...(ctx.has.http ? [HTTPX_REQUIREMENT] : [])];
  const description = ctx.spec.description.replace(/\s+/g, " ").trim() || ctx.spec.displayName;
  return `[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"

[project]
name = ${tomlStr(ctx.script)}
version = "${PACKAGE_VERSION}"
description = ${tomlStr(description)}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
${deps.map((d) => `    ${tomlStr(d)},`).join("\n")}
]

[project.optional-dependencies]
dev = ["pytest>=8"]

[project.scripts]
${tomlStr(ctx.script)} = "${ctx.pkg}.cli:main"
${tomlStr(ctx.script + "-evals")} = "${ctx.pkg}.evals:main"

[dependency-groups]
dev = ["pytest>=8"]

[tool.hatch.build.targets.wheel]
packages = ["${ctx.pkg}"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
`;
}

export function envExample(ctx: PyContext): string {
  const lines: string[] = [`# Environment for ${plain(ctx.spec.displayName, 80)}. Copy to .env and fill in.`, ""];
  const names = new Set<string>();
  const env = [...ctx.spec.env];
  if (!env.some((e) => e.name === "ANTHROPIC_API_KEY")) {
    env.unshift({ name: "ANTHROPIC_API_KEY", description: "Anthropic API key", required: true, secret: true });
  }
  for (const e of env) {
    if (names.has(e.name) || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(e.name)) continue;
    names.add(e.name);
    lines.push(`# ${plain(e.description, 160)}${e.required ? " (required)" : ""}${e.secret ? " [secret]" : ""}`);
    lines.push(`${e.name}=${e.default !== undefined && !e.secret ? envValue(e.default) : ""}`);
    lines.push("");
  }
  const P = ctx.envPrefix;
  lines.push(
    "# Harness overrides (optional)",
    `# ${P}_MODEL=${ctx.spec.model.id.replace(/[^\w.:[\]-]/g, "")}`,
    `# ${P}_SUBAGENT_MODEL=${ctx.spec.model.subagentId.replace(/[^\w.:[\]-]/g, "")}`,
    `# ${P}_PROJECT_ROOT=/path/to/your/project`,
    ...(ctx.has.memory ? [`# ${P}_MEMORY_DIR=./memories`] : []),
    "",
  );
  return lines.join("\n");
}

function approvalLabel(ctx: PyContext, t: { readOnly: boolean; destructive: boolean; requiresApproval: boolean }): string {
  const mode = ctx.spec.guardrails.approvalMode;
  if (mode === "never") return "no";
  if (mode === "always") return !t.readOnly || t.requiresApproval ? "yes" : "no";
  return t.requiresApproval || t.destructive ? "yes" : "no";
}

export function readmeMd(ctx: PyContext): string {
  const { spec, pkg, script } = ctx;
  const P = ctx.envPrefix;
  const g = spec.guardrails;
  const fence = "```";
  const env = spec.env.length
    ? spec.env
    : [{ name: "ANTHROPIC_API_KEY", description: "Anthropic API key", required: true, secret: true, default: undefined }];

  const toolRows = ctx.tools.map(
    (t) =>
      `| \`${mdCell(t.name)}\` | ${t.kind} | ${mdCell(t.description)} | ${t.readOnly ? "yes" : "no"} | ${t.destructive ? "yes" : "no"} | ${approvalLabel(ctx, t)} |`,
  );
  for (const s of ctx.subagents) {
    toolRows.push(
      `| \`${delegateToolName(s.name)}\` | subagent | ${mdCell(s.description)} | - | - | per subagent tool |`,
    );
  }

  const subagentSection = ctx.subagents.length
    ? `
## Subagents

Each subagent is a tool on the main agent. Calling it runs a nested agent loop with the
subagent's own system prompt, tool subset, model and effort, and returns its final report.

| Tool | Model | Effort | Tools |
|---|---|---|---|
${ctx.subagents
  .map(
    (s) =>
      `| \`${s.toolName}\` | ${mdCell(s.model ?? spec.model.subagentId)} | ${mdCell(s.effort ?? "medium")} | ${s.resolvedTools.map((n) => "`" + mdCell(n) + "`").join(", ") || "-"} |`,
  )
  .join("\n")}
`
    : "";

  return `# ${mdCell(spec.displayName)}

${mdCell(spec.description)}

A standalone Python agent harness generated by [decree-harness](https://github.com/TCYTseven/decree-app)
from \`decree.json\`. It runs Claude (\`${mdCell(spec.model.id)}\`, effort \`${spec.model.effort}\`) in a
streaming agent loop with the tools, guardrails and evals below.

## Setup

With [uv](https://docs.astral.sh/uv/):

${fence}bash
cp .env.example .env        # then fill in the values
uv run ${script} "your question"
uv run --group dev pytest    # tool smoke tests, no API key needed
${fence}

With pip:

${fence}bash
python3 -m venv .venv && . .venv/bin/activate
pip install -e ".[dev]"
cp .env.example .env
${script} "your question"
${fence}

Requires Python 3.10+. The CLI loads \`.env\` from the current directory and from this folder
(variables already set in the environment win).

## Usage

${fence}bash
${script}                          # interactive session (/cost, /reset, /help, /exit)
${script} "one-shot prompt"        # run once, stream the answer, exit
echo "prompt" | ${script} -        # prompt from stdin
python -m ${pkg} --help
${fence}

Tools operate on the **project root**: the current directory, \`${P}_PROJECT_ROOT\`, or \`--root\`.
Run it from the root of the codebase it was generated for.

Flags: \`--yes\` approves every tool call, \`--dry-run\` describes tool calls without running
them, \`--quiet\` hides tool activity, \`--thinking\` shows thinking output, \`--transcript FILE\`
saves the conversation as JSON. Exit code is 0 when the model finished normally, 2 when a guardrail
or refusal stopped it, 1 on errors.

## Environment

| Variable | Required | Secret | Description |
|---|---|---|---|
${env.map((e) => `| \`${mdCell(e.name)}\` | ${e.required ? "yes" : "no"} | ${e.secret ? "yes" : "no"} | ${mdCell(e.description)}${e.default !== undefined && !e.secret ? ` (default: \`${mdCell(e.default)}\`)` : ""} |`).join("\n")}
| \`${P}_MODEL\` | no | no | Override the main model (default \`${mdCell(spec.model.id)}\`). |
| \`${P}_SUBAGENT_MODEL\` | no | no | Override the default subagent model (default \`${mdCell(spec.model.subagentId)}\`). |
| \`${P}_PROJECT_ROOT\` | no | no | Directory the tools operate on (default: current directory). |
${ctx.has.memory ? `| \`${P}_MEMORY_DIR\` | no | no | Backing directory for the memory tool (default \`./memories\`). |\n` : ""}
## Tools

Approval mode is **${g.approvalMode}**: calls marked "yes" ask for a y/N confirmation first. A declined
call is reported back to the model, which is told to ask you how to proceed.

| Tool | Kind | Description | Read-only | Destructive | Needs approval |
|---|---|---|---|---|---|
${toolRows.join("\n")}
${subagentSection}
## Guardrails and context

- At most ${g.maxTurns} model requests per run, ${g.maxOutputTokensPerTurn} output tokens per request${g.maxCostUsd !== undefined ? `, and a stop once estimated spend passes $${g.maxCostUsd}` : ""}.
- Shell commands containing a blocked pattern are refused; file tools are confined to their root and to the allowed paths.
- Values of ${g.redactEnv.length ? g.redactEnv.map((n) => `\`${mdCell(n)}\``).join(", ") : "no environment variables"} are redacted from tool output.
- Prompt caching: ${spec.context.caching ? "on" : "off"}. Compaction: ${spec.context.compaction ? "on" : "off"}. Context editing: ${spec.context.contextEditing ? "on" : "off"}.

All of these live in \`${pkg}/config.py\`.

## Layout

| Path | What |
|---|---|
| \`${pkg}/config.py\` | Model, effort, guardrails, context strategy, pricing |
| \`${pkg}/prompt.py\` | System prompt${ctx.subagents.length ? "s" : ""} |
| \`${pkg}/tools/\` | Tool definitions (\`registry.py\`) and executors |
${ctx.subagents.length ? `| \`${pkg}/subagents.py\` | Subagent definitions and delegate tools |\n` : ""}| \`${pkg}/agent.py\` | The agent loop (\`Agent\`) |
| \`${pkg}/cli.py\` | Command line interface |
| \`${pkg}/evals.py\` | Eval runner |
| \`tests/test_tools.py\` | Offline tool tests |

## Extending

- **Add a tool**: append a \`ToolDef\` to \`TOOLS\` in \`${pkg}/tools/registry.py\` (kind \`http\`, \`shell\`,
  \`read_file\`, \`write_file\`, \`list_files\` or \`search\` reuse the built-in executors), or add a new kind and
  a branch in \`_dispatch\`. Set \`read_only\`/\`destructive\`/\`requires_approval\` honestly: they drive approvals
  and parallel execution.
- **Change the prompt**: edit \`${pkg}/prompt.py\`. Keep it free of timestamps so the cache prefix stays stable.
- **Use it as a library**:

${fence}python
from ${pkg}.agent import Agent

agent = Agent(approve=lambda tool, args: tool.read_only)
result = agent.run("...")
print(result.final_text, result.cost_usd)
${fence}

Regenerating with \`decree-harness generate\` overwrites these files; decree tracks hashes and will not
clobber files you have edited.

## Evals

${fence}bash
python -m ${pkg}.evals              # or: ${script}-evals
python -m ${pkg}.evals --case ${spec.evals[0] ? plain(spec.evals[0].id, 60).replace(/\s/g, "-") : "my-case"} --json
${fence}

Each case runs in a fresh agent. Checks: tools that must / must not be called, case-insensitive
substrings the answer must / must not contain, and an optional rubric graded by Claude. Tool calls that
need approval are declined unless you pass \`--yes\`. Exit code is 1 when any case fails.
`;
}
