import type { TsModel } from "../model.js";
import { str, templateBody, tsLiteral } from "../render.js";

export function configTs(m: TsModel): string {
  const { spec } = m;
  const g = spec.guardrails;
  const up = Array.from({ length: m.projectRootDepth }, () => `".."`).join(", ");
  const guardrails = {
    maxTurns: g.maxTurns,
    maxOutputTokensPerTurn: g.maxOutputTokensPerTurn,
    maxCostUsd: g.maxCostUsd,
    blockedCommands: g.blockedCommands,
    allowedPaths: g.allowedPaths,
    redactEnv: g.redactEnv,
    approvalMode: g.approvalMode,
  };
  const context = {
    caching: spec.context.caching,
    compaction: spec.context.compaction,
    contextEditing: spec.context.contextEditing,
  };

  return `/**
 * Harness configuration, generated by decree-harness from decree.json.
 * Everything here is plain data: edit it to change how the agent behaves.
 */
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/** The directory holding this package's package.json. */
export const PACKAGE_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

// Load ./.env when present (process.loadEnvFile needs Node >= 20.12; on older
// versions export the variables in your shell instead).
const envFile = path.join(PACKAGE_DIR, ".env");
if (existsSync(envFile) && typeof process.loadEnvFile === "function") process.loadEnvFile(envFile);

/** The project the agent works on. Every file and shell tool is confined to it. */
export const PROJECT_ROOT = path.resolve(process.env.PROJECT_ROOT ?? path.join(PACKAGE_DIR, ${up}));

/** Backing directory for the memory tool (the model sees it as /memories). */
export const MEMORY_DIR = path.join(PACKAGE_DIR, "memories");

export const AGENT_NAME = ${str(spec.displayName)};

export type Effort = "low" | "medium" | "high" | "xhigh" | "max";

export const MODEL: { id: string; effort: Effort; thinking: "adaptive" | "off" } = {
  id: process.env.AGENT_MODEL ?? ${str(spec.model.id)},
  effort: ${str(spec.model.effort)},
  thinking: ${str(spec.model.thinking)},
};

export interface Guardrails {
  /** Hard cap on model requests per run (subagents get the same cap). */
  maxTurns: number;
  maxOutputTokensPerTurn: number;
  /** Stop once the estimated spend of a run (including subagents) passes this. */
  maxCostUsd?: number;
  /** Shell commands containing any of these substrings are refused. */
  blockedCommands: string[];
  /** File tools may only touch paths under these roots (relative to PROJECT_ROOT). */
  allowedPaths: string[];
  /** Values of these env vars are scrubbed from tool output before the model sees it. */
  redactEnv: string[];
  /**
   * Who needs a human yes:
   * - "always": every tool that is not read-only, or that requires approval
   * - "destructive": tools marked destructive or requiring approval
   * - "never": nothing
   */
  approvalMode: "always" | "destructive" | "never";
}

export const GUARDRAILS: Guardrails = ${tsLiteral(guardrails)};

/**
 * Replace the value of every env var in GUARDRAILS.redactEnv with [REDACTED:<NAME>]
 * (longest values first; values shorter than 4 chars are ignored). Tools call it
 * before truncating output so a cut never leaves part of a secret behind.
 */
export function redact(text: string): string {
  const pairs = GUARDRAILS.redactEnv
    .map((name) => [name, process.env[name] ?? ""] as const)
    .filter(([, value]) => value.length >= 4)
    .sort((a, b) => b[1].length - a[1].length);
  let out = text;
  for (const [name, value] of pairs) out = out.split(value).join(\`[REDACTED:\${name}]\`);
  return out;
}

export interface ContextStrategy {
  /** Prompt caching: a breakpoint on the system prompt plus automatic caching of the conversation tail. */
  caching: boolean;
  /** Server-side compaction (beta) summarizes old turns when the context grows large. */
  compaction: boolean;
  /** Context editing (beta) clears old tool results. */
  contextEditing: boolean;
}

export const CONTEXT: ContextStrategy = ${tsLiteral(context)};
`;
}

export function promptTs(m: TsModel): string {
  return `/**
 * The system prompt, generated from decree.json. Keep it stable: it is the
 * cached prefix of every request, so edits invalidate the prompt cache once.
 */
export const SYSTEM_PROMPT = \`${templateBody(m.spec.systemPrompt)}\`;
`;
}
