import type { ToolSpec } from "../../../core/types.js";
import type { TsModel } from "../model.js";
import { mdCell, oneLine } from "../render.js";

function approvalLabel(tool: ToolSpec, mode: TsModel["spec"]["guardrails"]["approvalMode"]): string {
  const needs =
    mode === "never" ? false : mode === "always" ? !tool.readOnly || tool.requiresApproval : tool.requiresApproval || tool.destructive;
  return needs ? "yes" : "no";
}

export function readmeMd(m: TsModel): string {
  const { spec } = m;
  const g = spec.guardrails;
  const out: string[] = [];
  const push = (...lines: string[]) => out.push(...lines);

  push(`# ${oneLine(spec.displayName)}`, "", oneLine(spec.description), "");
  push(`**Goal:** ${oneLine(spec.goal)}`, "");
  push(
    "A standalone agent harness for Claude, generated by [decree-harness](https://github.com/TCYTseven/decree-app)",
    "from `decree.json`. It is plain TypeScript on the Anthropic SDK: read it, own it, change it.",
    "",
  );

  push("## Setup", "", "```sh", "npm install", "cp .env.example .env   # then fill in the values", "```", "");
  push("Requires Node 18.17+ (Node 20.12+ to load `.env` automatically; otherwise export the variables).", "");

  push("## Run", "", "```sh", 'npm start -- "your request"   # one-shot', "npm start                     # interactive chat", "```", "");
  push(
    "In chat, `/reset` clears the conversation, `/cost` shows the estimated spend and `/exit` quits.",
    "Tools that need approval ask `[y/N]` first; `--yes` approves everything (use with care).",
    "Without a terminal, such tools are declined.",
    "",
  );

  push("## Environment", "", "| Variable | Required | Secret | Description |", "|---|---|---|---|");
  for (const env of m.env) {
    const def = env.default ? ` (default \`${mdCell(env.default).replace(/`/g, "'")}\`)` : "";
    push(`| \`${mdCell(env.name)}\` | ${env.required ? "yes" : "no"} | ${env.secret ? "yes" : "no"} | ${mdCell(env.description)}${def} |`);
  }
  push(
    "| `PROJECT_ROOT` | no | no | Project the agent works on (defaults to the project this was generated for). |",
    "| `AGENT_MODEL` | no | no | Overrides the model id. |",
    "",
  );

  push("## Tools", "", `Approval mode: \`${g.approvalMode}\`.`, "", "| Tool | Kind | Read-only | Destructive | Needs approval | Description |", "|---|---|---|---|---|---|");
  for (const t of m.tools) {
    const s = t.spec;
    push(
      `| \`${t.name}\` | ${s.kind} | ${s.readOnly ? "yes" : "no"} | ${s.destructive ? "yes" : "no"} | ${approvalLabel(s, g.approvalMode)} | ${mdCell(s.description)} |`,
    );
  }
  push("");
  if (m.subagents.length > 0) {
    push("### Subagents", "", "Each subagent is a `delegate_to_*` tool that runs its own loop with a subset of the tools.", "");
    push("| Tool | Model | Tools | When |", "|---|---|---|---|");
    for (const s of m.subagents) {
      push(`| \`${s.toolName}\` | ${mdCell(s.model)} (${s.effort}) | ${s.tools.map((t) => `\`${t}\``).join(", ")} | ${mdCell(s.description)} |`);
    }
    push("");
  }

  push(
    "## Guardrails",
    "",
    `- At most ${g.maxTurns} model turns per run, ${g.maxOutputTokensPerTurn} output tokens per turn.`,
    g.maxCostUsd !== undefined ? `- Stops once the estimated cost of a run passes $${g.maxCostUsd}.` : "- No cost cap (set `maxCostUsd` in `src/config.ts`).",
    g.blockedCommands.length > 0
      ? `- Shell commands containing any of ${g.blockedCommands.map((c) => `\`${oneLine(c).replace(/`/g, "'")}\``).join(", ")} are refused.`
      : "- No blocked shell patterns.",
    `- File tools are confined to ${g.allowedPaths.map((p) => `\`${oneLine(p).replace(/`/g, "'")}\``).join(", ") || "nothing"} under the project root (symlinks included).`,
    g.redactEnv.length > 0 ? `- Values of ${g.redactEnv.map((e) => `\`${e}\``).join(", ")} are redacted from tool output.` : "- No env values are redacted.",
    "",
  );

  push("## Layout", "", "```");
  const layout: [string, string][] = [
    ["src/cli.ts", "one-shot and interactive entry point"],
    ["src/agent.ts", "runAgent(): system prompt + tools + loop"],
    ["src/loop.ts", "the agent loop (streaming, tools, approvals, caching, stop reasons)"],
    ["src/config.ts", "model, guardrails, context strategy"],
    ["src/prompt.ts", "the system prompt"],
    ["src/tools/index.ts", "tool registry: definitions, flags, executors"],
  ];
  if (m.subagents.length > 0) layout.push(["src/subagents.ts", "delegate_to_* tools"]);
  if (m.kinds.has("decisions")) layout.push(["src/tools/decisions.ts", "get_decisions: decisions that govern the given paths"], ["decisions.json", "the team decisions, written from decree.json"]);
  layout.push(["src/evals.ts", "eval runner"]);
  const width = Math.max(...layout.map(([p]) => p.length));
  for (const [p, what] of layout) push(`${p.padEnd(width)}  ${what}`);
  push("```", "");

  push(
    "## Extending",
    "",
    "- **Add a tool:** append an entry to `TOOLS` in `src/tools/index.ts` with a `definition` (name, description,",
    "  JSON Schema `input_schema`), safety flags, and a `run(input)` returning `{ output, isError }`. Append rather",
    "  than reorder: the tool list is part of the cached prompt prefix.",
    "- **Change behavior:** edit `src/prompt.ts` (the system prompt) or `src/config.ts` (model, effort, guardrails,",
    "  caching, compaction).",
    "- **Embed it:** `import { runAgent } from \"./src/agent.js\"` and call",
    "  `runAgent({ prompt, history, approve, onEvent })`; pass `result.messages` as `history` to continue.",
    "",
    "Note: re-running `decree-harness generate` rewrites these files; decree keeps a manifest and will not",
    "clobber files you have edited unless you ask it to.",
    "",
  );

  push(
    "## Evals",
    "",
    "```sh",
    "npm run eval               # all cases",
    "npm run eval -- <case-id>  # selected cases",
    "```",
    "",
    "Cases are read from `../evals.json` when present, otherwise from the copy embedded in `src/evals.ts`.",
    "Each case checks which tools were (not) called, what the answer contains, and optionally a rubric graded",
    "by a Claude judge. Destructive tools are always declined during evals. The command exits 1 on any failure.",
    "",
  );
  return out.join("\n");
}
